events {
    worker_connections 1024;
}

http {
    upstream nextjs_app {
        server frontend:3000;
    }

    server {
        listen 80;
        server_name madukotawatte-erp.centralindia.cloudapp.azure.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name madukotawatte-erp.centralindia.cloudapp.azure.com;

        ssl_certificate     /etc/letsencrypt/live/madukotawatte-erp.centralindia.cloudapp.azure.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/madukotawatte-erp.centralindia.cloudapp.azure.com/privkey.pem;

        client_max_body_size 20M;   # allow image uploads for Crop Doctor later

        location / {
            proxy_pass         http://nextjs_app;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout 60s;
        }
    }
}
